### ISSUE TITLE
Blank gap under Friends icon after BetterDiscord update?

### ISSUE THREAD

**Issue by georgem8** [Dyzean/Simplify#3]
After BetterDiscord update 11/02/21, there is now a blank gap below the Friends icon and above servers list

![image](https://user-images.githubusercontent.com/27610185/140023249-9188b7de-7cd2-4592-a16e-a5007b5193ba.png)

**Comment by Dinoslav** [comment]
> After BetterDiscord update 11/02/21, there is now a blank gap below the Friends icon and above servers list
> 
> ![image](https://user-images.githubusercontent.com/27610185/140023249-9188b7de-7cd2-4592-a16e-a5007b5193ba.png)

Same issue, did you fix it?

**Comment by Krazytrain** [comment]
> > After BetterDiscord update 11/02/21, there is now a blank gap below the Friends icon and above servers list
> > ![image](https://user-images.githubusercontent.com/27610185/140023249-9188b7de-7cd2-4592-a16e-a5007b5193ba.png)
> 
> Same issue, did you fix it?

Thank me later!
Add this at the bottom of the theme file:

.wrapper-3NnKdC > ul > .scroller-1Bvpku > div[aria-label="Servers"] {
  margin-top: 0px;
}

**Comment by Dinoslav** [comment]
> > > After BetterDiscord update 11/02/21, there is now a blank gap below the Friends icon and above servers list
> > > ![image](https://user-images.githubusercontent.com/27610185/140023249-9188b7de-7cd2-4592-a16e-a5007b5193ba.png)
> > 
> > 
> > Same issue, did you fix it?
> 
> Thank me later! Add this at the bottom of the theme file:
> 
> .wrapper-3NnKdC > ul > .scroller-1Bvpku > div[aria-label="Servers"] { margin-top: 0px; }

Didn't help sadly 
![image](https://user-images.githubusercontent.com/68663248/148643616-91ddc328-cd76-4bdb-a3f1-901e5ca1623e.png)

**Comment by Dyzean** [comment]
I'm very sorry for the very late response, i'll try pushing a commit for this rq.

**Comment by Dyzean** [comment]
Just pushed a commit, can somekne test it if its working fine now?

**Comment by Dinoslav** [comment]
> Just pushed a commit, can someone test if its working fine now?

Works like a charm! Thanks alot

**Comment by Dyzean** [comment]
Cool, im sorry again for the late response 👍🏼
