### ISSUE TITLE
requst: hide channel list

### ISSUE THREAD

**Issue by SeniorMars** [Dyzean/Simplify#8]
Hello, I was wondering if it was possible to hide channels like [this](https://images-ext-1.discordapp.net/external/6ckN1-U7aTJGVpLoa-fc6NhH-npkMqy10YSpaukoBMQ/https/i.imgur.com/aGX7hGg.mp4)?

**Comment by Krazytrain** [comment]
Just put this in css editor.
You can thank me later but I don't see why you would need it.

/* Collapse Channel List and reveals it on hover */
  div.sidebar-1tnWFu
  {
    width: 50px;
    transition: width 0.3s;
  }

  div.sidebar-1tnWFu:hover
  {
    width: 240px;
  }

**Comment by Krazytrain** [comment]
#7 I have also fixed the color reaction too.

**Comment by Krazytrain** [comment]
@KarlWithK  Iv changed it to the way member list is. Iv spent far too long on this for no reason.
There is a problem with it tho the DM list messes up.

/* Collapse Channel List and reveals it on hover */
.container-1NXEtd, .sidebar-1tnWFu{
  z-index: 3;
  width: 60px;
  min-width: 60px;
  transition-property: width, min-width;
  transition-duration: 600ms;
}
.container-1NXEtd:hover{
    width: 300px;
    min-width: 300px;
    position: absolute;
}
